### ISSUE TITLE
Transfer recalculations

### ISSUE THREAD

**Issue by Whiz652** [isathar/Blender-Normal-Editing-Tools#2]
Normals that was not edited by transfer recalculated as default blender normals and 'Selected Only' does some strange stuff on transfer.

Despite this your add on is very useful for welding seams of multimesh characters, thanks a lot :+1:

**Comment by isathar** [comment]
Thanks for the feedback, and I'm glad you like it. (That feature started as an accidental side-effect, btw. :) )
The issues with the transfer function should be fixed in the most recent commit.
